/*
									 Include-ul principal ce leaga toate fisirele de pe intregul GameMode
									In acest include, se regasesc aproape toate sistemele pentru ca unele,
												sunt in uz de catre #tryinclude din alte fisiere.



								   *** Author - Kurama - GameMode GF created since 23 - February - 2018 ***
								   						(c) Copyrighted for our community.
*/
#if defined GF_Kurama_Base_GM_included
	#endinput
#else
	#define GF_Kurama_Base_GM_included
#endif

#include <a_samp>
#include <crashdetect>
#include <GF_functii/GF_original_streamer>
#include <GF_functii/GF_original_sscanf2>
#include <GF_functii/GF_original_zcmd>
#include <GF_functii/GF_original_foreach>
#include <GF_functii/GF_original_format_number>
#include <GF_functii/GF_original_rotate_object>
#include <GF_functii/GF_original_mysql>
#include <GF_functii/GF_DefComune>							   						
#include <GF_functii/GF_Factiuni>
#include <GF_functii/GF_OnPlayerDisconnect>
#include <GF_functii/GF_AFKSystem>
#include <GF_functii/GF_Teritorii>
#include <GF_functii/GF_WarSystem>
#include <GF_functii/GF_OnPlayerDeath>
#include <GF_functii/GF_HousesSystem>
#include <GF_functii/GF_BusinessSystem>
#include <GF_functii/GF_VehiclesSystems>
#include <GF_functii/GF_FunctiileMele>
#include <GF_functii/GF_JobsSystems>
#include <GF_functii/GF_ObjectsGM>
#include <GF_functii/GF_OnPlayerCheckpoint>
#include <GF_functii/GF_SafesSystem>
#include <GF_functii/GF_OnPlayerPickup>
#include <GF_functii/GF_OnDialogResponse>
#include <GF_functii/GF_WantedSystem>
#include <GF_functii/GF_RadioCarSystem>
#include <GF_functii/GF_private/GameMode_ClassSkinSel>
#include <GF_functii/GF_private/GF_DealershipSystem-private>
#include <GF_functii/GF_private/GF_PayDaySystem-private>
#include <GF_functii/GF_EnterExitFunc>
#include <GF_functii/GF_private/GF_FireMissionSystem-private>
#include <GF_functii/GF_private/GF_RegisterSystem-private>
#include <GF_functii/GF_private/GF_BanPlayerSystem-private>
#include <GF_functii/GF_private/GF_AntiCheatSystem-private>
#include <GF_functii/GF_private/GF_LicenseSystem-private>
#include <GF_functii/GF_private/GF_MissionsDaily-private>
#include <GF_functii/GF_TimeingFunctions>
#include <GF_functii/GF_private/GF_FlyPlayerSystem-private>
#include <GF_functii/GF_GunsFunc>
#include <GF_functii/GF_CommandsGen>
#include <GF_functii/GF_private/GF_MySQLFunc-private>
#include <GF_functii/GF_private/GF_SpikesSystem-private>
#include <GF_functii/GF_private/GF_WalkieTalkie-private>
#include <GF_functii/GF_private/GF_Menu03xFunc-private>
#include <GF_functii/GF_private/GF_FishingSystem-private>
#include <GF_functii/GF_private/GF_ReferralSystem-private>
#include <GF_functii/GF_RobberySystem>
#include <GF_functii/GF_private/GF_RaceSys-private>

// End Of File ...
